README.md
lib/prom_ex.ex
lib/prom_ex/config.ex
lib/prom_ex/metrics_server/plug.ex
test/prom_ex/metrics_server/plug_test.exs

Adding auth support to standalone metrics server.
Prometheus offers the ability to pass bearer and basic auth headers to the scrape source. This change will allow the standalone server to respect and check those headers if configured to do so. Auth support will only be implemented for the standalone server given that the Phoenix plug can leverage Unplug to do the same thing and can be catered to the specific needs of the user.

Initial work on metrics server auth support

---

lib/core/counter.ex
lib/core/distribution.ex
lib/core/last_value.ex
lib/core/sum.ex
lib/prom_ex/debug.ex
lib/prom_ex/plugins/ecto.ex
lib/prom_ex/plugins/oban.ex

Changed from local capture to module.function capture when using :telemetry.attach
I didn't run benchmarks on this, just following the guidance from the docs below.
> Note: due to how anonymous functions are implemented in the Erlang VM, it is best to use function captures (i.e. fun mod:fun/4 in Erlang or &Mod.fun/4 in Elixir) as event handlers to achieve maximum performance. In other words, avoid using literal anonymous functions (fun(...) -> ... end or fn ... -> ... end) or local function captures (fun handle_event/4 or &handle_event/4 ) as event handlers.
[Telemetry docs](https://hexdocs.pm/telemetry/)

Use module.function capture for event handling

---

lib/prom_ex/plugins/oban.ex

Add a case for `normalize_module_name` matching tuples which extracts the Plugin name from it.
See #34 
- Since `normalize_module_name` is private and I am not sure how to test it: No
- No, since it's a private function

Add normalize for Oban.Plugin with options

---

.github/workflows/main.yml
lib/prom_ex.ex
test/prom_ex_test.exs

Telemetry poller expects :period instead of :poll_rate.

Fix poller period

---

lib/mix/tasks/prom_ex.dashboard.export.ex

Added the user configured assigns from the `PromEx` module to the rendering in `Mix.Tasks.PromEx.Dashboard.Export`.
I feel like there was an omission in the dashboard exporter, please correct me if that was wrong, but my thinking was that it's easiest to discuss with the proposed change.
Happy to discuss tests if required and change desired.
I setup my configuration as described in the docs, so that my `PromEx` default module was generated as expected.
When running the exporter (`Mix.Tasks.PromEx.Dashboard.Export`) for example like this:
```
mix prom_ex.dashboard.export --dashboard ecto.json --stdout  
```
I was expecting the assigns of the `PromEx` module to be used (it's the default module in my project and I checked that it was used). But those assigns are not actually used in the …

[Fix] Include module dashboard assigns in export

---

lib/prom_ex/config.ex
lib/prom_ex/dashboard_uploader.ex
lib/prom_ex/grafana_client.ex
lib/prom_ex/grafana_client/connection.ex
lib/prom_ex/lifecycle_annotator.ex
test/prom_ex/grafana_client/connection_test.exs

Adds requested changes for feature request #45. I can add more tests and/or `PromEx.Config` grafana opts validation, but wanted to get feedback on if this is a desired direction first.
I originally was only going to do the following:
- Update `PromEx.Config` to make `auth_token` no longer required
- Update `PromEx.GrafanaClient.Connection` to only add `Bearer #{auth_token}` if `not is_nil(auth_token)`
- Update `PromEx.GrafanaClient` to only add `Bearer #{auth_token}` header if `not is_nil(auth_token)`
However, `Finch` removes any trace of Basic Auth from the url passed to `Finch.Request`. So I ended up having to add `:username` and `:password` values to the header manually via `Basic #{Base.encode64("#{username}:#{password}")}`
#45 
```elixir
config :vms, VMS.PromEx,
grafana: [
host: …
```

Enable Grafana Basic Auth

---

lib/prom_ex/plugins/phoenix.ex

`PromEx.Plugins.Phoenix` should return 0 as a measurment for `"http.response.size.bytes"` if the response body is empty.
In my app I have a plug that checks session value and redirects to root page if the user id is missing or the user has no access due to role.
I noticed an error in PromEx when such redirects occurred:
```
01:10:30.111 [error] Handler {PromEx.TelemetryMetricsPrometheus.Core.EventHandler, #PID<0.3719.0>, [:my_app, :prom_ex, :phoenix, :http, :response, :size, :bytes]} has failed and has been detach
ed. Class=:error
Reason=:badarg
Stacktrace=[{:erlang, :iolist_size, [nil], []}, {PromEx.Plugins.Phoenix, :"-http_events/2-fun-0-", 2, [file: 'lib/prom_ex/plugins/phoenix.ex', line: 96]}, {PromEx.TelemetryMetricsPrometheus.Core.Eve
ntHandler, :get_measurement, 3, [file: …
```

Fix for responses with empty body

---

priv/beam.json.eex

Updating a description in one of the BEAM dashboard's panels to remove a typo.
I'm using PromEx now and can't use the grafana dashboard as-is (short of it is we need additional filters to get at the metrics and don't have the plugins you reference in our hosted grafana), but while porting the promex dashboard to my company's grafana models, I noticed the typo.
Teeny contribution, but hoping one of many.

Fix typo in beam dashboard

---

lib/mix/tasks/prom_ex.dashboard.export.ex
test/mix/tasks/prom_ex.dashboard.export_test.exs

The --stdout flag in the docs was incorrect (was `std_out`, but should be `stdout`). Fixed the docs and added a test for verification.
The use of the more verbose flag failed with a runtime exception saying the --std_out flag was invalid.

Fix documentation for the --stdout flag

---

lib/prom_ex/plugins/ecto.ex

Update the description for the `ecto` plugin results returned query.

Fix comments for the ecto results query

---

lib/mix/tasks/prom_ex.dashboard.export.ex
lib/prom_ex/dashboard_renderer.ex
lib/prom_ex/plugins/absinthe.ex
lib/prom_ex/plugins/application.ex
lib/prom_ex/plugins/beam.ex
lib/prom_ex/plugins/ecto.ex
lib/prom_ex/plugins/oban.ex
lib/prom_ex/plugins/phoenix.ex
lib/prom_ex/plugins/phoenix_live_view.ex
lib/prom_ex/plugins/prom_ex.ex
priv/absinthe.json.eex
priv/application.json.eex
priv/beam.json.eex
priv/ecto.json.eex
priv/oban.json.eex
priv/phoenix.json.eex
priv/phoenix_live_view.json.eex
test/mix/tasks/prom_ex.dashboard.export_test.exs

Allow overriding the `PromEx.metric_prefix/2` from `plugins/0` configuration.
As a consultancy, we have many applications and want to make a more generic set of dashboards. To do this we need applications outputting the same set of metric names. With this, we can let `prom_ex_#{plugin}` be the lead of the metric and not have the specific application in place.
```
def plugins() do
[
{Plugins.Application, metric_prefix: [:prom_ex, :application]},
{Plugins.Beam, metric_prefix: [:prom_ex, :beam]},
{Plugins.Phoenix, metric_prefix: [:prom_ex, :phoenix], router: Web.Router},
{Plugins.Ecto, metric_prefix: [:prom_ex, :ecto]},
{Plugins.Oban, metric_prefix: [:prom_ex, :oban], oban_supervisors: [Oban]},
{Plugins.PromEx, metric_prefix: [:prom_ex, :prom_ex]}
]
end
```
We …

Add an optional `metric_prefix` option to plugins

---

README.md
lib/prom_ex/plugins/plug_cowboy.ex
priv/plug_cowboy.json.eex
test/support/metrics/plug_cowboy.txt

- An option `metric_prefix` was added in akoutmos/prom_ex#83, but
wasn't applied to the PlugCowboy plugin
- Add readme line item about cowboy plugin
- Fix wording in one cowboy metric help text
- Adjust cowboy default dashboard for new metrix_prefix
Add `metric_prefix` to cowboy plugin
Tested with plugins configured like...
```elixir
{Plugins.Application, metric_prefix: [:prom_ex, :application]},
{Plugins.Beam, metric_prefix: [:prom_ex, :beam]},
{Plugins.Ecto, metric_prefix: [:prom_ex, :ecto]},
{Plugins.Phoenix,
metric_prefix: [:prom_ex, :phoenix], router: Redacted.Router, event_prefix: [:spidey, :endpoint]},
{Plugins.PlugCowboy,
metric_prefix: [:prom_ex, :cowboy], routers: [Redacted.Router], ignore_routes: ["/metrics"]},
{Plugins.PromEx, metric_prefix: [:prom_ex, :prom_ex]}
```

Add metrix_prefix option to Cowboy plugin

---

example_applications/web_app/lib/web_app_web/telemetry.ex
lib/prom_ex/plugins/ecto.ex
test/support/metrics/ecto.txt

All other measurments included in ecto for query timing were already included in the ecto plugin of prom_ex.
:total_time was missing, which put the burden on the end user doing a long series of sum()'s in prometheus.
Missing ecto :total_time metric.
- [ecto description of total_time](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/repo.ex#L148)
- [ecto_sql setting of total_time](https://github.com/elixir-ecto/ecto_sql/blob/master/lib/ecto/adapters/sql.ex#L951)

Adds :total_time metric to ecto plugin

---

lib/prom_ex/plugins/plug_router.ex

handles request without `conn.private.plug_route` info
- sets path tag as `Unknown` for those cases
- allows ignoring a request by comparing the `:ignore_routes` option values against the request `conn.request_path` when no `conn.private.plug_route` is present
Issue number: #95
Plugin usage continues to be the same

Fix PlugRouter to handle request not resolved by Plug.Router

---

mix.exs

Bump `finch` dependency to `0.9.0`
Currently, we have some dependencies that do not play well together:
With `master` `prom_ex` (`phoenix` at `1.6.0`) and `finch` at `0.8.0`:
```
Failed to use "telemetry" (version 1.0.0) because
deps/promex/mix.exs requires ~> 1.0.0
ecto_sql (version 3.7.1) requires ~> 0.4.0 or ~> 1.0
finch (version 0.8.0) requires ~> 0.4
```
With `master` `prom_ex` and `finch` at `0.9.0`, which is compatible with `telemetry` `1.0.0`:
```
Failed to use "finch" (version 0.9.0) because
deps/promex/mix.exs requires ~> 0.8.0
mix.lock specifies 0.9.0
```
This PR updates `finch` so everything plays nicely together.
- [N/A] I have added unit tests to cover my changes.
- [N/A] I have added documentation to cover my changes.

Bump finch version

---

lib/prom_ex/lifecycle_annotator.ex

Hello,
I propose to remove these logs entries as not having those variable set won't cause any problem. Or maybe better, we could not add these git related informations in the annotation if they are not present. What do you think?
It avoid noise in logs.

Remove warning logs about missing GIT_* env vars

---

mix.exs

Make source links in docs link to the correct branch
Getting to a 404 when clicking such a link
https://hexdocs.pm/ex_doc/Mix.Tasks.Docs.html
> `:source_ref` - The branch/commit/tag used for source link inference; default: "main".

Make source links in docs link to the correct branch

---

lib/prom_ex/plugins/broadway.ex

Closes #114
Added a section to the Broadway plugin documentation that points out the use of a transform to add correct 'acknowledger'.
Incorrectly tagged values that cannot be found by the Grafana Broadway dashboard, when the 'acknowledger' is set to the default, namely the name of the Broadway producer module.
Issue number: #114
Examine docs to verify the change.
Built docs

Add documentation for needed transform to Broadway

---

priv/broadway.json.eex

Change text and description of the 'Message Error Percentage' panels in Grafana broadway.json dashboard to name them as 'Message Success Percentage' instead.
Currently the calculation and coloring (green-to-red) defines 100% as no errors and all successes. The text and description of the panels are reversed to the actual.
Here a screenshot from a run with no errors:
Issue number: N/A
No usage
None

Fix Grafana broadway.json to name message percentages as success rates

---

lib/prom_ex.ex
lib/prom_ex/dashboard_uploader.ex
lib/prom_ex/grafana_client.ex
lib/prom_ex/lifecycle_annotator.ex
test/prom_ex/dashboard_uploader_test.exs
test/prom_ex/grafana_client_test.exs
test/prom_ex/lifecycle_annotator_test.exs

Makes `PromEx.GrafanaClient` more generally useful beyond supporting the dashboard uploader and the lifecycle annotations.
[Slack Thread](https://elixir-lang.slack.com/archives/C01NZ0FBFSR/p1644012540991449)
```elixir
conn = GrafanaClient.build_conn(MyApp.PromEx)
{:ok, _} = 
GrafanaClient.create_annotation(conn, ["some", "tags"], "something happened",
time: ~U[2022-01-01 00:00:00Z],
time_end: ~U[2022-01-02 00:00:00Z],
dashboard_id: 1,
panel_id: 2
)
```

Grafana client generalization

---

mix.exs

Allows upgrading of Telemetry once https://github.com/beam-telemetry/telemetry_metrics_prometheus_core/pull/45 is released.

Relax telemetry versioning requirement

---

lib/prom_ex/plugins/broadway.ex
test/prom_ex/plugins/broadway_test.exs

While using `BroadwayRabbitMQ.Producer`for  Broadway, we were not able to override the message acknowledger according to the docs as there is a unique `:delivery_tag` required to ack messages to RMQ.   When we tried, this was empty and our messages were not being acked.
Second, the metrics were not showing up for the RabbitMQ backed pipeline, but they were for a pipeline using a normal GenStage producer and after some digging around, I noticed that the `:name` tag/label on the `/metrics` were different:
```bash
broadway_process_message_duration_milliseconds_count{batcher="local",name="Prom.Pipelines.LocalPipeline"}
```
```bash
broadway_process_message_duration_milliseconds_count{batcher="rabbit",name="BroadwayRabbitMQ.Producer"}
```
After switching the tag_values function to use …

Fix: Use topology name for message and exception tags

---

guides/howtos/Telemetry.md

Fixes the telemetry example, which had the incorrect order of arguments.  According to the [telemetry docs](https://hexdocs.pm/telemetry/telemetry.html#attach/4) the event name is supposed to be the second argument, not the first.  It was also unclear what `query_event` was referring to as it appears no where else in the documentation.
N/A
Issue number: N/A
N/A
N/A

fix-telemetry-example

---

lib/prom_ex/plugins/ecto.ex

support for missing repo config

---

lib/mix/tasks/prom_ex.dashboard.publish.ex

Added a function to start PromEx.GrafanaClient before calling upload dashboard. When uploading dashboard this will fix the issue where Finch is not found
Issue number: #127

start GrafanaClient in prom_ex.dashboard.publish (#127)

---

CHANGELOG.md
lib/prom_ex/grafana_agent/downloader.ex
test/prom_ex/grafana_agent/downloader_test.exs

This change adds FreeBSD support by automatically downloading the grafana agent FreeBSD build.
GitHub actions doesn't support FreeBSD, but [Cirrus CI does](https://cirrus-ci.org/guide/FreeBSD/). I also added a Cirrus CI config for FreeBSD.
I don't have an example application to share, but we have used this branch to push data and graphs to AWS managed Prometheus and Grafana (it worked great!)

Download Grafana Agent on FreeBSD

---

guides/howtos/Writing PromEx Plugins.md

Fix prom_ex plugin docs - change "our" to "out"
Docs update
n/a
n/a
n/a

Fix prom_ex plugin docs - change "our" to "out"

---

guides/howtos/Running Multiple Agents.md
lib/mix/tasks/prom_ex.gen.config.ex
lib/prom_ex/config.ex
lib/prom_ex/grafana_agent.ex
lib/prom_ex/grafana_agent/downloader.ex
mix.exs
priv/grafana_agent/default_config.yml.eex
test/mix/tasks/prom_ex.gen.config_test.exs
test/prom_ex/grafana_agent/config_renderer_test.exs
test/prom_ex/grafana_agent/downloader_test.exs
test/prom_ex/grafana_agent/expected_output_config.yml

- Permit parallel grafana agent downloader processes
- Configure grafana agent gRPC port
- Add `-m` option to generator to specify PromEx module name
This allows us to configure multiple PromEx processes within our own application.
We want to record metrics and publish dashboards to multiple sources (e.g. one for ops team, and one for biz team).
Configure multiple PromEx processes and add them each to the supervisor:
```elixir
config :my_app, Core.PromExBiz,
...
grafana: [
host: "http://localhost:3000",
...
folder_name: "myapp-biz"
],
grafana_agent: [
working_directory: Path.expand(".grafana_biz"),
config_opts: [
metrics_server_path: "/metrics/biz",
...
instance: "dev-biz",
prometheus_url: "http://prometheus-biz:9090/api/v1/write",
...
agent_port: 4040,
grpc_port: 9040
]
]
config :my_app, …
```

Run multiple Grafana Agent processes

---

lib/prom_ex/config.ex
lib/prom_ex/grafana_agent/config_renderer.ex
test/prom_ex/grafana_agent/config_renderer_test.exs

Adds a `template_file` config to override the built-in grafana agent config template.
We have multiple agent configs that differ from the built-in config template. We found it was elegant to provide our own template file, and let PromEx specify any defaults and pass through our new custom config keys.
```elixir
config :my_app, MyApp.PromEx,
grafana_agent: [
...
config_opts: [
...
template_file: Application.app_dir(:my_app, "priv/templates/grafana_agent_config.eex"),
custom_field: "custom value" # available as <%= @custom_field %> in the template
]
]
```

Configurable Grafana Agent template

---

guides/howtos/Seeding Metrics.md
mix.exs

This adds a guide for seeding telemetry events on application start.
After restarting a service (when a new release is deployed, for example), periodic telemetry may not appear for some spans of time. This can result in Grafana showing "No Data", rather than 0-value data points.

Add guide for seeding metrics

---

lib/prom_ex/config.ex
test/prom_ex/config_test.exs

#159 was missing a commit that we had on a different branch when testing. Sorry for not being more careful there.
This permits template_file to be overridden, and for additional variables to be passed through to the template file.
The config currently passes an explicit list of keys to grafana agent config. Any keys not in that list will not get sent.
This change allows us to send additional grafana agent config keys that will be passed through to the template file.
It's necessary to enable the functionality of #159 - without it, a `template_file` config won't get passed to the grafana agent config.
We have deployed this branch to production and confirmed that it fixes the problem described above.

Override and pass in additional grafana agent config keys

---

lib/prom_ex/config.ex

Adds missing comma in PromEx.Config docs example.

Fix typo in PromEx.Config docs

---

lib/prom_ex/plugins/absinthe.ex
lib/prom_ex/plugins/application.ex
lib/prom_ex/plugins/beam.ex
lib/prom_ex/plugins/broadway.ex
lib/prom_ex/plugins/ecto.ex
lib/prom_ex/plugins/oban.ex
lib/prom_ex/plugins/phoenix.ex
lib/prom_ex/plugins/phoenix_live_view.ex
lib/prom_ex/plugins/plug_cowboy.ex
lib/prom_ex/plugins/plug_router.ex
lib/prom_ex/utils.ex

This change adds a new optional option to the `Ecto` plugin configuration - `duration_unit`.
It allows the user to override the time unit of the `Ecto` metrics, allowing to directly pass it through to `:telemetry`.
Issue number: #139 
```elixir
{Plugins.Ecto, [repos: [Shared.Repo], duration_unit: :second]}
```

Add  `duration_unit` option to Ecto plugin

---

CHANGELOG.md
lib/prom_ex/dashboard_uploader.ex
lib/prom_ex/grafana_client.ex
test/prom_ex/dashboard_uploader_test.exs

If the folder UID changes for any reason prom_ex gets stuck in a crash loop that takes down the VM.
Issue number: #176 
~~None of the Grafana client functionality appears to have test coverage this time.~~ edit: sorry, checked the wrong test modules

Fix application crashing on startup

---

lib/prom_ex/plugins/phoenix.ex
test/prom_ex/ets_cron_flusher_test.exs
test/prom_ex/plugins/phoenix_test.exs
test/support/events/phoenix.exs
test/support/metrics.ex
test/support/metrics/phoenix.txt

Adds the event name that is present  from the [`channel_handled_in` telemetry payload](https://hexdocs.pm/phoenix/Phoenix.Logger.html) as a tag for the duration metric. 
I also noticed that `:handler` was included in the `tags` field, but wasn't actually set under `tag_values`. Maybe this was a bug? I added it as a tag value as well.
There's a lot of value including this tag with duration metrics. Right now, if a specific event handler function is slow, there's no way to identify that with without the `event` dimension. With it added, it's now possible to group by events and monitor for slow handlers.
Nothing really required from the user's side to set this up, they'll just need to update their PromEx version. `channel_handled_in_duration_milliseconds` metrics will now include the `event` …

Include event and handler name as tags with handle_in metrics

---

README.md

If you start PromEx before the Endpoint, it will raise an error `RuntimeError: ** (RuntimeError) could not find persistent term for endpoint` at least once, until the Endpoint started.
It works, but can pollute your logs (and will be very annoying if you have something like AppSignal running in production)
Issue number: #194

Add supervisor start instructions

---

mix.exs

Change range of telemetry from `~> 1.0` to `>= 1.0.0` to allow for newer versions of `:telemetry` (currently `1.2.1` is the latest)
Issue number: #164

Allow versions of telemetry newer than 1.0

---

lib/prom_ex/config.ex
lib/prom_ex/grafana_agent.ex
lib/prom_ex/grafana_agent/downloader.ex
priv/grafana_agent/default_config.yml.eex
test/prom_ex/grafana_agent/config_renderer_test.exs
test/prom_ex/grafana_agent/expected_output_config_post_v0_26.yml

This adds support for Grafana Agent v0.29.0
Per the [Grafana Agent CHANGELOG](https://github.com/grafana/agent/blob/03b9598a4c8d70877a79d634c441d1d26609599f/CHANGELOG.md#v0260-2022-07-18), the pertinent breaking change is that `server.http_listen_port` and `server.grpc_listen_port` have been removed from the config file, and moved to command line args `-server.http.address` and `-server.grpc.address` respectively.
This change adds support for both - pre v0.26.0 is unchanged, v0.26.0 and above omits the removed keys from the default config, and passes them as flags.
It maintains v0.23.0 as the default, to not affect existing installations.
We are running this commit in prod.
We ran into a problem where after rebooting a machine, Grafana Agent got stuck in a crash loop trying to replay the …

Add support Grafana Agent v0.29.0

---

guides/howtos/Writing PromEx Plugins.md

Just a typo. The function name in the `reporter_options` is [exponential!](https://hexdocs.pm/prom_ex/PromEx.BucketGenerator.html#exponential!/3) (with a `!`).
Saves folks who copy/paste a few minutes of confusion 😄

Fix typo in example plugin documentation

---

lib/prom_ex/dashboard_uploader.ex

This adds the configuration variable `title`to `dashboard_assigns`, making it possible to use a different name for the dashboard, other than MyProject.
I have multiple versions of the same codebase running, thus in my Grafana the Dashboards get overriden since they all have the same otp_name.
```elixir
def dashboard_assigns do
[
datasource_id: PetalPro.config(:prometheus_datasource_id),
default_selected_interval: "30s",
title: "ainomaly.io"
]
end
```

makes the dashboard title configurable.

---

lib/prom_ex.ex
lib/prom_ex/storage.ex
lib/prom_ex/storage/core.ex

Preliminary work for supporting different storages beyond `telemetry_metrics_prometheus_core`.
Support implementing alternative storage backends (like [Peep][]) for users that require different performance characteristics.
[Peep]: https://github.com/rkallos/peep

ft: implement pluggable storage

---

lib/prom_ex/metric_types/polling.ex

docs: clarify detach_on_error

---

lib/prom_ex/plugins/oban.ex

The newly added opts for Polling.build/5 are not passed from the Oban plugin when called like so: 
```
{Plugins.Oban, oban_supervisors: [Oban], poll_rate: 10_000, opts: [detach_on_error: false]}
```
https://github.com/akoutmos/prom_ex/issues/236
https://github.com/akoutmos/prom_ex/commit/3feecebb979ac4b46f8326f45b1e699ad550673e

Pass along new polling_opts

---

lib/prom_ex/plugins/phoenix.ex

The current logic for the `keep_endpoint_metrics` function doesn't work for cases where multiple endpoints are configured using the `endpoints:` key.
This change normalizes the endpoints config to work with `module in phoenix_endpoints`
The events defined in the `endpoint_info` function weren't working as expected, as the `keep_function_filter` returned false. This started happening after I tested out the config for multiple endpoints.

Phoenix Plugin: Correctly support multiple endpoints
